kind: Secret
apiVersion: v1
metadata:
  name: remote-kafka-secrets
stringData:
   REMOTE_KAFKA_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required  oauth.client.id="KafkaConsole"  oauth.client.secret="${{CLIENT_SECRET}}"  oauth.token.endpoint.uri="https://${{SSO_HOST}}/realms/${{SSO_REALM}}/protocol/openid-connect/token"  oauth.valid.issuer.uri="https://${{SSO_HOST}}/realms/${{SSO_REALM}}"  oauth.jwks.endpoint.uri="https://${{SSO_HOST}}/realms/${{SSO_REALM}}/protocol/openid-connect/certs"  oauth.username.claim="client_id";'
type: Opaque
